# Generated by Django 6.1.1 on 2026-09-07 23:05

import uuid
from django.db import migrations, models


def prepare_existing_readings(apps, schema_editor):
    Reading = apps.get_model('readings', 'Reading')
    for reading in Reading.objects.all().iterator():
        reading.share_token = uuid.uuid4()
        reading.status = 'ready' if reading.ai_response else 'failed'
        reading.save(update_fields=('share_token', 'status'))


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0002_reading_reading_user_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="mode",
            field=models.CharField(
                choices=[("classic", "Clásico"), ("negative", "Negativo")],
                default="classic",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="model_used",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="share_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("ready", "Lista"),
                    ("failed", "Fallida"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="tokens_used",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reading",
            name="ai_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(prepare_existing_readings, migrations.RunPython.noop),
    ]
