# Generated by Django 6.1.1 on 2026-09-07 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "readings",
            "0003_reading_mode_reading_model_used_reading_share_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
