# Generated by Django 6.1.1 on 2026-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0004_alter_reading_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="address_as",
            field=models.CharField(
                choices=[
                    ("masculine", "Masculino"),
                    ("feminine", "Femenino"),
                    ("neutral", "Neutro"),
                ],
                default="neutral",
                editable=False,
                max_length=10,
                verbose_name="preferencia de tratamiento al generar",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
