# Generated by Django 6.1.1 on 2026-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0008_readingfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="mode",
            field=models.CharField(
                choices=[
                    ("classic", "Clásico"),
                    ("negative", "Negativo"),
                    ("roast", "Roast"),
                ],
                default="classic",
                max_length=10,
            ),
        ),
    ]
