# Generated by Django 6.1.1 on 2026-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_plan_user_plan_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_as",
            field=models.CharField(
                choices=[
                    ("masculine", "Masculino"),
                    ("feminine", "Femenino"),
                    ("neutral", "Neutro"),
                ],
                default="neutral",
                max_length=10,
                verbose_name="preferencia de tratamiento",
            ),
        ),
    ]
