# Generated by Django 6.1.1 on 2026-09-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarotcard",
            name="suit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wands", "Bastos"),
                    ("cups", "Copas"),
                    ("swords", "Espadas"),
                    ("pentacles", "Oros"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
